### ISSUE TITLE
Метод Pay изменяет значение баланса на большую сумму, чем текущий баланс

### ISSUE THREAD

**Issue by Nastysshaaa** [gitkornienkov/coop_work#2]
# Описание
Метод Pay изменяет значение balance на большее, чем initialBalance.

# Локация дефекта
https://github.com/gitkornienkov/coop_work/blob/e6899fd1942b027252282390b3833e957ee810d9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L45

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/gitkornienkov/coop_work/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA.
2. В тесте создать класс SavingAccount через конструктор введя следующие параметры:
- initialBalance: 2_000,
- minBalance: 1_000,
- maxBalance: 10_000,
- rate: 5
3. Вызвать метод Pay со значением amount 3_000
4. Запустить тест
5. Посмотреть на вывод в консоли
*Ожидаемый результат:* Тест проходит. Значение баланса 2_000
*Фактический результат:* Тест не проходит. Значение баланса -1_000

# Скриншот
![Скрин для баг-репорта 2](https://user-images.githubusercontent.com/123237244/231803607-dbf22155-e103-4907-82fe-bd151f15adfc.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.3.2
* **Java:** OpenJDK 11

**Comment by gitkornienkov** [comment]
Fixed
