### ISSUE TITLE
Отрицательный баланс при оплате (метод Pay) на сумму больше, чем минимальный баланс

### ISSUE THREAD

**Issue by Nastysshaaa** [gitkornienkov/coop_work#4]
# Описание
Метод Pay изменяет значение balance на отрицательный.

# Локация дефекта
https://github.com/gitkornienkov/coop_work/blob/e6899fd1942b027252282390b3833e957ee810d9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L45

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/gitkornienkov/coop_work/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA.
2. В тесте создать класс SavingAccount через конструктор введя следующие параметры:
- initialBalance: 2_000,
- minBalance: 1_000,
- maxBalance: 10_000,
- rate: 5
3. Вызвать метод Pay со значением amount 20_000
4. Запустить тест
5. Посмотреть на вывод в консоли
*Ожидаемый результат:* Тест проходит. Значение баланса 2_000
*Фактический результат:* Тест не проходит. Значение баланса -18_000

# Скриншот
![Скрин для баг-репорта 4](https://user-images.githubusercontent.com/123237244/231999054-938249a9-0a60-4221-b203-dcdab8c2922c.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.3.2
* **Java:** OpenJDK 11

**Comment by gitkornienkov** [comment]
Fixed
