### ISSUE TITLE
При пополнении счета (метод Add) сумма текущего баланса стала меньше, чем минимальный баланс 

### ISSUE THREAD

**Issue by Nastysshaaa** [gitkornienkov/coop_work#5]
# Описание
Метод Add изменяет значение balance на сумму меньшую, чем минимальный баланс

# Локация дефекта
https://github.com/gitkornienkov/coop_work/blob/e6899fd1942b027252282390b3833e957ee810d9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L69

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/gitkornienkov/coop_work/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA.
2. В тесте создать класс SavingAccount через конструктор введя следующие параметры:
- initialBalance: 2_000,
- minBalance: 1_000,
- maxBalance: 10_000,
- rate: 5
3. Вызвать метод Add со значением amount 500
4. Запустить тест
5. Посмотреть на вывод в консоли
*Ожидаемый результат:* Тест проходит. Значение баланса 2_500
*Фактический результат:* Тест не проходит. Значение баланса 500

# Скриншот
![Скрин для баг-репорта 5](https://user-images.githubusercontent.com/123237244/232209842-3dcea03c-5c4e-4bd5-8098-96a2a081c040.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.3.2
* **Java:** OpenJDK 11

**Comment by gitkornienkov** [comment]
Fixed
