### ISSUE TITLE
Не выбрасывается исключение при отрицательном текущем балансе (initialBalance) в классе SavingAccount

### ISSUE THREAD

**Issue by Nastysshaaa** [gitkornienkov/coop_work#6]
# Описание
При установке отрицательного текущего баланса (initialBalance) в классе SavingAccount не выбрасывается исключение IllegalArgumentException

# Локация дефекта
https://github.com/gitkornienkov/coop_work/blob/e6899fd1942b027252282390b3833e957ee810d9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/gitkornienkov/coop_work/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA.
2. В тесте создать класс SavingAccount через конструктор введя следующие параметры:
- initialBalance: -2_000,
- minBalance: 1_000,
- maxBalance: 10_000,
- rate: 5
3. Запустить тест
4. Посмотреть на вывод в консоли
*Ожидаемый результат:* Выбрасывается исключение о недопустимости отрицательного начального баланса
*Фактический результат:* Исключение отсутствует

# Скриншот
![Скрин для баг-репорта 6](https://user-images.githubusercontent.com/123237244/232212588-3866aa4e-d195-4e7d-bf79-0b6102f9506d.png)

#Тест
https://github.com/gitkornienkov/coop_work/blob/e6899fd1942b027252282390b3833e957ee810d9/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L309-L319

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA 2022.3.2
* **Java:** OpenJDK 11

**Comment by gitkornienkov** [comment]
Fixed
